spacing = 0.10000000149011612
hit_effect = true
kill_effect = true
hit_effect_volume = 1.0
kill_effect_volume = 1.0

[hit_colours_initial]
r = 1.0
g = 0.0
b = 0.5

[hit_colours_final]
r = 0.0
g = 0.0
b = 0.0

[kill_colours_initial]
r = 0.2
g = 0.1
b = 0.1

[kill_colours_final]
r = 1.0
g = 0.5
b = 0.6
